### ISSUE TITLE
Purolator tracking scan times are incorrectly parsed

### ISSUE THREAD

**Issue by crbn60** [Purplship/purplship#105]
The times reported in a TrackingEvent from Purolator seem to be incorrectly parsed as seconds instead of the HHMMSS format Purolator weirdly uses.

This is the debug output to console for the tracking number I am testing with (note the `<ScanTime>100625</ScanTime>`):

```xml
       <Scan i:type="DeliveryScan">
            <ScanType>Delivery</ScanType>
            <PIN>
                <Value>607460066279</Value>
            </PIN>
            <Depot>
                <Name>130 IBER RD, STITTSVILLE, ON, K2S1E9</Name>
            </Depot>
            <ScanDate>2021-01-25</ScanDate>
            <ScanTime>100625</ScanTime>
            <Description>Shipment delivered</Description>
            <Comment/>
            <SummaryScanIndicator>false</SummaryScanIndicator>
            <ScanDetails>
                <DeliverySignature>LYY</DeliverySignature>
                <SignatureImage/>
                <SignatureImageSize>0</SignatureImageSize>
                <SignatureImageFormat>GIF</SignatureImageFormat>
                <DeliveryAddress>STITTSVILLE, ON</DeliveryAddress>
                <DeliveryCompanyName/>
                <PremiumServiceText>Not known or specified</PremiumServiceText>
                <ProductTypeText>Regular</ProductTypeText>
                <SpecialHandlingText/>
                <PaymentTypeText>Sender</PaymentTypeText>
            </ScanDetails>
        </Scan>
```
And here is the `TrackingEvent` object that is returned (note the `time='03:57'`:
```python
TrackingEvent(date='2021-01-25', description='Shipment delivered', location='130 IBER RD, STITTSVILLE, ON, K2S1E9', code='Delivery', time='03:57')
```
And here is what the Purolator website shows:
<img width="793" alt="image" src="https://user-images.githubusercontent.com/1441946/115926189-6ee87880-a450-11eb-8004-d3f1824564ac.png">

I poked around in the code, and it seems like it may be treating `100625` as seconds instead of _HHMMSS_?

**Comment by DanH91** [comment]
Hey @crbn60,

Thanks for pointing that out. You are right it was parsed as a timestamp instead of `HHMMSS `

https://github.com/Purplship/purplship/blob/ed577394cd454b4980ca4665e5226d9bf195c783/extensions/purolator_courier/purplship/providers/purolator_courier/tracking.py#L48

I will issue a fix ASAP

**Comment by DanH91** [comment]
Hey @crbn60,

This should be fixed in https://github.com/Purplship/purplship/pull/106
I have released the patch https://pypi.org/project/purplship.purolator-courier/ so if you upgrade to version `2021.3.1` you should be good.

I will close the issue. Feel free to open an issue if there is anything else 

Let me know

**Comment by crbn60** [comment]
Thank you _very_ much for the super fast turnaround time @DanH91 , it works perfectly.
